apiVersion: v1
kind: Secret
metadata:
  name: notification-secret
stringData:
  GMAIL_ADDRESS: "sweasytech63@gmail.com" #must be changed
  GMAIL_PASSWORD: "ceUnYcexiiRTM7WJ4rWVd" #must be changed
type: Opaque